### ISSUE TITLE
W3C に怒られるのだ

### ISSUE THREAD

**Issue by Siketyan** [approvers/dockerps-web#2]
そんな HTML 属性はないのだー！

https://github.com/approvers/dockerps-web/blob/96f78252e833bee6063ef98b983ef0808ed52800/template.html#L82

**Comment by kawaemon** [comment]
CSSのセレクタのためっぽいのだ

**Comment by Siketyan** [comment]
data-status とかにするといいのだ！

**Comment by loxygenK** [comment]
ごめんなさいなのだ…すぐ修正するのだ…
